/**
 * Catalogue éditorial EvPortal — septembre 2026.
 * Vérifications, limites et sources : docs/LIENS.md.
 * Couleurs des monogrammes utilisés lorsque le logo local est indisponible.
 * Un lien accessible ne garantit pas la lecture sur un navigateur embarqué.
 */
window.EV_CATALOG = {
  version: "2026-09-curated",
  categories: [
    {
      id: "cinema",
      label: "Cinéma & vidéo",
      description: "Films, séries et vidéos pour votre pause.",
      shortcuts: [
        {"serviceId":"netflix","name":"Netflix","url":"https://www.netflix.com/","description":"Films, séries et documentaires à la demande.","color":"#ff6b7a","tag":"Compte requis","categoryIds":["cinema"]},
        {"serviceId":"plex","name":"Plex","url":"https://app.plex.tv/","description":"Votre médiathèque et des programmes en streaming.","color":"#f3c45b","categoryIds":["cinema"]},
        {"serviceId":"prime-video","name":"Prime Video","url":"https://www.primevideo.com/","description":"Films, séries et créations Amazon à la demande.","color":"#58c6f0","tag":"Compte requis","categoryIds":["cinema"]},
        {"serviceId":"disney-plus","name":"Disney+","url":"https://www.disneyplus.com/","description":"Films et séries Disney, Pixar, Marvel et plus.","color":"#929dff","tag":"Compte requis","categoryIds":["cinema"]},
        {"serviceId":"hbo-max","name":"HBO Max","url":"https://www.hbomax.com/","description":"Films, séries HBO et documentaires à la demande.","color":"#b79aff","tag":"Compte requis","categoryIds":["cinema"]},
        {"serviceId":"paramount-plus","name":"Paramount+","url":"https://www.paramountplus.com/fr/","description":"Films, séries et créations originales Paramount.","color":"#82a9ff","tag":"Compte requis","categoryIds":["cinema"]},
        {"serviceId":"pluto-tv","name":"Pluto TV","url":"https://pluto.tv/","description":"Chaînes en direct et programmes à la demande.","color":"#f2d266","categoryIds":["cinema","tv"],"legacyAliases":[{"name":"Pluto TV","url":"https://pluto.tv/fr/"},{"name":"Pluto TV","url":"https://pluto.tv/fr/watch/live-tv/"},{"name":"Pluto TV","url":"https://pluto.tv/live-tv"},{"name":"PlutoTV","url":"https://pluto.tv/fr/"},{"name":"PlutoTV","url":"https://pluto.tv/fr/watch/live-tv/"},{"name":"PlutoTV","url":"https://pluto.tv/live-tv"}]},
        {"serviceId":"crave","name":"Crave","url":"https://www.crave.ca/fr","description":"Films et séries pour les spectateurs au Canada.","color":"#ec678e","tag":"Selon région","categoryIds":["cinema"],"countries":["CA"]},
        {"serviceId":"starz","name":"Starz","url":"https://www.starz.com/","description":"Séries originales et cinéma du catalogue STARZ.","color":"#ec678e","tag":"Selon région","categoryIds":["cinema"],"countries":["US"]},
        {"serviceId":"dazn","name":"DAZN","url":"https://www.dazn.com/","description":"Retransmissions et programmes consacrés au sport.","color":"#ec678e","tag":"Compte requis","categoryIds":["cinema"]},
        {"serviceId":"canal-plus","name":"CANAL+","url":"https://www.canalplus.com/","description":"Cinéma, séries, sport et chaînes du groupe CANAL+.","color":"#d4dce6","tag":"Compte requis","categoryIds":["cinema","tv"],"legacyAliases":[{"name":"CANAL+","url":"https://www.canalplus.com/"},{"name":"Canal+","url":"https://www.canalplus.com/"}]},
        {"serviceId":"apple-tv","name":"Apple TV","url":"https://tv.apple.com/fr","description":"Séries originales et films du catalogue Apple TV.","color":"#cbd3df","tag":"Compte requis","categoryIds":["cinema"]},
        {"serviceId":"youtube","name":"YouTube","url":"https://www.youtube.com/","description":"Vidéos, chaînes et créations à découvrir en ligne.","color":"#ff777b","categoryIds":["cinema"]},
        {"serviceId":"rakuten-tv","name":"Rakuten TV","url":"https://www.rakuten.tv/fr/gardens/free","description":"Une sélection de films en streaming avec publicité.","color":"#ec678e","categoryIds":["cinema"]},
        {"serviceId":"justwatch","name":"JustWatch","url":"https://www.justwatch.com/fr","description":"Trouvez où regarder un film ou une série en streaming.","color":"#ff6b7a","categoryIds":["cinema"]},
        {"serviceId":"onf","name":"ONF — Office national du film","url":"https://www.onf.ca/","description":"Documentaires et films d’animation de l’Office national du film du Canada.","color":"#ff6b7a","categoryIds":["cinema"]},
      ],
    },
    {
      id: "music",
      label: "Musique & radio",
      description: "Vos morceaux, radios et podcasts préférés.",
      shortcuts: [
        {"serviceId":"apple-music","name":"Apple Music","url":"https://music.apple.com/","description":"Votre musique et vos playlists dans le navigateur.","color":"#fa80a1","tag":"Compte requis","categoryIds":["music"]},
        {"serviceId":"spotify","name":"Spotify","url":"https://open.spotify.com/","description":"Musique, playlists et podcasts dans le lecteur web.","color":"#65db91","tag":"Compte requis","categoryIds":["music"]},
        {"serviceId":"deezer","name":"Deezer","url":"https://www.deezer.com/fr/channels/explore","description":"Musique et playlists depuis la version française.","color":"#bd8aff","tag":"Compte requis","categoryIds":["music"]},
        {"serviceId":"soundcloud","name":"SoundCloud","url":"https://soundcloud.com/","description":"Morceaux, artistes indépendants et découvertes audio.","color":"#ffad76","categoryIds":["music"]},
        {"serviceId":"youtube-music","name":"YouTube Music","url":"https://music.youtube.com/","description":"Musique, clips et playlists du catalogue YouTube.","color":"#ff878e","categoryIds":["music"]},
        {"serviceId":"tidal","name":"TIDAL","url":"https://listen.tidal.com/","description":"Le lecteur web pour votre bibliothèque musicale.","color":"#a48cff","tag":"Compte requis","categoryIds":["music"]},
        {"serviceId":"qobuz","name":"Qobuz","url":"https://play.qobuz.com/","description":"Écoutez vos albums depuis le lecteur web Qobuz.","color":"#a48cff","tag":"Compte requis","categoryIds":["music"]},
        {"serviceId":"bandcamp","name":"Bandcamp","url":"https://bandcamp.com/","description":"Albums et découvertes des artistes indépendants.","color":"#a48cff","categoryIds":["music"]},
        {"serviceId":"accuradio","name":"AccuRadio","url":"https://www.accuradio.com/","description":"Radios musicales classées par genres et ambiances.","color":"#a48cff","categoryIds":["music"]},
        {"serviceId":"iheartradio","name":"iHeartRadio","url":"https://www.iheart.com/","description":"Radios et podcasts, selon votre zone géographique.","color":"#a48cff","tag":"Selon région","categoryIds":["music"],"countries":["US","CA","MX","AU","NZ"]},
        {"serviceId":"mixcloud","name":"Mixcloud","url":"https://www.mixcloud.com/","description":"Mix, émissions musicales et créations de DJ.","color":"#a48cff","categoryIds":["music"]},
        {"serviceId":"liveone","name":"LiveOne","url":"https://www.liveone.com/","description":"Radios, musique et programmes audio en streaming.","color":"#a48cff","categoryIds":["music"]},
        {"serviceId":"idagio","name":"IDAGIO","url":"https://www.idagio.com/","description":"Une bibliothèque dédiée à la musique classique.","color":"#a48cff","tag":"Compte requis","categoryIds":["music"]},
        {"serviceId":"tunein","name":"TuneIn","url":"https://tunein.com/radio/home/","description":"Radios en direct, actualité et podcasts du monde.","color":"#a48cff","categoryIds":["music"]},
        {"serviceId":"radio-france","name":"Radio France","url":"https://www.radiofrance.fr/","description":"Radios publiques, émissions et podcasts en français.","color":"#a48cff","categoryIds":["music"]},
        {"serviceId":"fip","name":"FIP","url":"https://www.radiofrance.fr/fip","description":"Une radio musicale éclectique et ses webradios.","color":"#f18fc5","categoryIds":["music"]},
        {"serviceId":"france-inter","name":"France Inter","url":"https://www.radiofrance.fr/franceinter","description":"Écoutez le direct et les podcasts de France Inter.","color":"#a48cff","categoryIds":["music"]},
        {"serviceId":"france-culture","name":"France Culture","url":"https://www.radiofrance.fr/franceculture","description":"Émissions, documentaires et podcasts culturels.","color":"#a48cff","categoryIds":["music"]},
        {"serviceId":"radio-garden","name":"Radio Garden","url":"https://radio.garden/","description":"Explorez les radios du monde sur un globe interactif.","color":"#a48cff","tag":"Selon région","categoryIds":["music"]},
        {"serviceId":"somafm","name":"SomaFM","url":"https://somafm.com/","description":"Radios indépendantes sans publicité, par genres et ambiances.","color":"#fa80a1","categoryIds":["music"]},
        {"serviceId":"radio-paradise","name":"Radio Paradise","url":"https://radioparadise.com/","description":"Une radio musicale éclectique et ses différents mix.","color":"#fa80a1","categoryIds":["music"]},
        {"serviceId":"mynoise","name":"myNoise","url":"https://mynoise.net/","description":"Ambiances sonores et sons de nature personnalisables.","color":"#fa80a1","categoryIds":["music"]},
      ],
    },
    {
      id: "tv",
      label: "Télévision",
      description: "Les directs et replays à portée de main.",
      shortcuts: [
        {"serviceId":"molotov","name":"Molotov","url":"https://www.molotov.tv/","description":"Télévision et replay selon les offres disponibles.","color":"#61b8ff","tag":"Compte requis","categoryIds":["tv"],"countries":["FR"]},
        {"serviceId":"france-tv","name":"france.tv","url":"https://www.france.tv/","description":"Les directs et replays de France Télévisions.","color":"#61b8ff","tag":"Compte requis","categoryIds":["tv"]},
        {"serviceId":"tf1-plus","name":"TF1+","url":"https://www.tf1.fr/","description":"Émissions, séries et direct sur la plateforme TF1+.","color":"#61b8ff","tag":"Compte requis","categoryIds":["tv"],"countries":["FR","BE","LU","CH","DZ","BJ","BF","CM","KM","CI","DJ","GA","GN","MU","MG","ML","MA","MR","NE","CG","CD","RW","SN","TD","TG","TN"]},
        {"serviceId":"m6-plus","name":"M6+","url":"https://www.m6.fr/","description":"Émissions, séries et replays des chaînes du groupe M6.","color":"#61b8ff","tag":"Compte requis","categoryIds":["tv"]},
        {"serviceId":"arte","name":"ARTE","url":"https://www.arte.tv/fr/","description":"Documentaires, cinéma et programmes culturels.","color":"#ff966b","categoryIds":["tv"]},
        {"serviceId":"tv5mondeplus","name":"TV5MONDEplus","url":"https://www.tv5mondeplus.com/fr","description":"Films, séries et documentaires de la francophonie.","color":"#61b8ff","categoryIds":["tv"]},
        {"serviceId":"rtbf-auvio","name":"RTBF Auvio","url":"https://auvio.rtbf.be/direct","description":"Directs et replays belges ; certains programmes sont réservés à la Belgique.","color":"#61b8ff","tag":"Selon région","categoryIds":["tv"],"countries":["BE"]},
        {"serviceId":"gulli","name":"Gulli","url":"https://www.m6.fr/gulli/direct","description":"Accès au direct Gulli sur la plateforme M6+.","color":"#ec678e","categoryIds":["tv"],"legacyCategoryIds":["cinema","tv"],"legacyAliases":[{"name":"Replay Gulli","url":"https://replay.gulli.fr/Direct"}]},
        {"serviceId":"nasa-plus","name":"NASA+","url":"https://plus.nasa.gov/","description":"Missions, directs et documentaires de la NASA.","color":"#61b8ff","categoryIds":["tv"]},
      ],
    },
    {
      id: "charging",
      label: "Recharge",
      description: "Trouvez une borne et préparez vos étapes.",
      shortcuts: [
        {"serviceId":"chargepoint","name":"ChargePoint","url":"https://driver.chargepoint.com/","description":"Carte des bornes du réseau et informations utiles.","color":"#efa16e","categoryIds":["charging"]},
        {"serviceId":"abrp","name":"ABRP","url":"https://abetterrouteplanner.com/","description":"Planifiez vos trajets et vos arrêts de recharge.","color":"#77c3ef","categoryIds":["charging","navigation"],"legacyAliases":[{"name":"ABRP","url":"https://abetterrouteplanner.com/"}]},
        {"serviceId":"plugshare","name":"PlugShare","url":"https://www.plugshare.com/","description":"Carte des bornes et retours de la communauté VE.","color":"#71dcab","categoryIds":["charging"]},
        {"serviceId":"tesla-superchargeurs","name":"Tesla Superchargeurs","url":"https://www.tesla.com/fr_fr/findus","description":"Localisez les stations Superchargeurs de Tesla.","color":"#ff7b83","categoryIds":["charging"]},
        {"serviceId":"chargemap","name":"Chargemap","url":"https://chargemap.com/fr-fr/map","description":"Carte des bornes, connecteurs et avis des conducteurs.","color":"#63cbb9","categoryIds":["charging"]},
        {"serviceId":"chargeprice","name":"Chargeprice","url":"https://fr.chargeprice.app/","description":"Comparez les tarifs de recharge selon vos cartes.","color":"#71dcab","categoryIds":["charging"]},
        {"serviceId":"ionity","name":"IONITY","url":"https://www.ionity.eu/network","description":"Carte des stations du réseau de recharge européen.","color":"#da8fcd","categoryIds":["charging"]},
        {"serviceId":"electra","name":"Electra","url":"https://stations.go-electra.com/fr","description":"Trouvez les stations et informations du réseau Electra.","color":"#71dcab","categoryIds":["charging"]},
        {"serviceId":"fastned","name":"Fastned","url":"https://www.fastnedcharging.com/fr/emplacements","description":"Carte des stations de recharge du réseau Fastned.","color":"#f3cf5f","categoryIds":["charging"]},
        {"serviceId":"freshmile","name":"Freshmile","url":"https://charge.freshmile.com/map","description":"Repérez les bornes accessibles avec le réseau Freshmile.","color":"#71dcab","categoryIds":["charging"]},
        {"serviceId":"chargefinder","name":"ChargeFinder","url":"https://chargefinder.com/fr","description":"Carte des bornes et informations sur leur disponibilité.","color":"#71dcab","categoryIds":["charging"]},
        {"serviceId":"electricity-maps","name":"Electricity Maps","url":"https://app.electricitymaps.com/","description":"Visualisez le mix électrique et son intensité carbone.","color":"#efa16e","categoryIds":["charging"]},
      ],
    },
    {
      id: "games",
      label: "Jeux",
      description: "Une pause ludique, directement sur le web.",
      shortcuts: [
        {"serviceId":"geforce-now","name":"GeForce NOW","url":"https://play.geforcenow.com/","description":"Accédez à vos jeux PC via le service cloud NVIDIA.","color":"#b2d86b","tag":"Compte requis","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"airconsole","name":"AirConsole","url":"https://www.airconsole.com/","description":"Jeux multijoueurs avec un téléphone comme manette.","color":"#eeae63","tag":"Téléphone requis","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"2048","name":"2048","url":"https://jeu2048.fr/","description":"Assemblez les tuiles pour atteindre le nombre 2048.","color":"#eeae63","categoryIds":["games"]},
        {"serviceId":"solitaire","name":"Solitaire","url":"https://solitaire.com/","description":"Une partie de cartes à lancer dans le navigateur.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"demineur","name":"Démineur","url":"https://minesweeperonline.com/","description":"Retrouvez les mines avec logique et déduction.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"snake","name":"Snake","url":"https://playsnake.org/","description":"Le jeu du serpent pour une courte pause ludique.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"chess-com","name":"Chess.com","url":"https://www.chess.com/","description":"Parties, exercices et apprentissage des échecs.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"crazygames","name":"CrazyGames","url":"https://www.crazygames.com/fr/","description":"Une sélection de jeux à lancer dans le navigateur.","color":"#eeae63","categoryIds":["games"]},
        {"serviceId":"jeux-fr","name":"Jeux.fr","url":"https://www.jeux.fr/","description":"Jeux de réflexion, de cartes et petites aventures.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"1001-jeux","name":"1001 Jeux","url":"https://www.1001jeux.fr/","description":"Des jeux de navigateur classés par catégories.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"poki","name":"Poki","url":"https://poki.com/fr","description":"Jeux de réflexion, de course et aventures en ligne.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"jeux-gratuits-com","name":"Jeux-Gratuits.com","url":"https://www.jeux-gratuits.com/","description":"Jeux de cartes, logique et divertissements en ligne.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"playhop","name":"PlayHop","url":"https://playhop.com/fr","description":"Un catalogue de jeux à découvrir dans le navigateur.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"lichess","name":"Lichess","url":"https://lichess.org/fr","description":"Échecs en ligne, entraînement et défis de logique.","color":"#eeae63","tag":"Sans publicité","categoryIds":["games"]},
        {"serviceId":"sudoku","name":"Sudoku","url":"https://sudoku.com/fr","description":"Grilles de sudoku en français, du facile à l’expert.","color":"#eeae63","categoryIds":["games"],"defaultIncluded":false},
        {"serviceId":"little-alchemy-2","name":"Little Alchemy 2","url":"https://littlealchemy2.com/","description":"Combinez des éléments et découvrez de nouvelles créations.","color":"#b2d86b","categoryIds":["games"]},
        {"serviceId":"infinite-craft","name":"Infinite Craft","url":"https://neal.fun/infinite-craft/","description":"Associez des éléments pour inventer de nouvelles combinaisons.","color":"#b2d86b","categoryIds":["games"]},
      ],
    },
    {
      id: "navigation",
      label: "Navigation & trafic",
      description: "Préparez la route et consultez le trafic.",
      shortcuts: [
        {"serviceId":"google-maps","name":"Google Maps","url":"https://maps.google.com/","description":"Recherchez un lieu et préparez votre prochain trajet.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"waze","name":"Waze","url":"https://www.waze.com/live-map/?locale=fr","description":"Carte du trafic et préparation de vos itinéraires.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"apple-plans","name":"Apple Plans","url":"https://maps.apple.com/","description":"Lieux, cartes et itinéraires dans Apple Plans web.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"here-wego","name":"HERE WeGo","url":"https://wego.here.com/","description":"Cartes et calcul d’itinéraires pour vos déplacements.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"openstreetmap","name":"OpenStreetMap","url":"https://www.openstreetmap.org/","description":"La carte collaborative pour explorer les environs.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"mapquest","name":"MapQuest","url":"https://www.mapquest.com/","description":"Cartes et itinéraires, notamment en Amérique du Nord.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"bing-maps","name":"Bing Maps","url":"https://www.bing.com/maps","description":"Recherchez des lieux et consultez les cartes Bing.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"tomtom-plan","name":"TomTom Plan","url":"https://plan.tomtom.com/","description":"Préparez vos parcours dans le planificateur web.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"infotrafic","name":"Infotrafic","url":"https://www.infotrafic.com/","description":"Informations de circulation et état du réseau routier.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"bison-fute","name":"Bison Futé","url":"https://www.bison-fute.gouv.fr/zoommaintenant.html","description":"Carte officielle du trafic et des événements routiers.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"sytadin","name":"Sytadin","url":"https://www.sytadin.fr/","description":"Trafic et temps de parcours des routes d’Île-de-France.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"wikivoyage","name":"Wikivoyage","url":"https://fr.wikivoyage.org/wiki/Accueil","description":"Guides de voyage collaboratifs pour préparer vos étapes.","color":"#5ac9db","categoryIds":["navigation"]},
        {"serviceId":"atlas-obscura","name":"Atlas Obscura","url":"https://www.atlasobscura.com/","description":"Découvrez des lieux insolites et des idées d’escapades.","color":"#5ac9db","categoryIds":["navigation"]},
      ],
    },
    {
      id: "social",
      label: "Réseaux sociaux",
      description: "Retrouvez vos proches et vos communautés.",
      shortcuts: [
        {"serviceId":"facebook","name":"Facebook","url":"https://www.facebook.com/","description":"Actualités de vos proches, groupes et communautés.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"x","name":"X","url":"https://x.com/","description":"Publications et conversations sur vos sujets suivis.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"instagram","name":"Instagram","url":"https://www.instagram.com/","description":"Photos, vidéos et nouvelles de vos comptes suivis.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"linkedin","name":"LinkedIn","url":"https://www.linkedin.com/","description":"Votre réseau professionnel et ses publications.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"snapchat","name":"Snapchat","url":"https://web.snapchat.com/","description":"Vos conversations dans la version web de Snapchat.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"tiktok","name":"TikTok","url":"https://www.tiktok.com/","description":"Vidéos courtes et créateurs à découvrir en ligne.","color":"#99a9ff","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"reddit","name":"Reddit","url":"https://www.reddit.com/","description":"Discussions et communautés autour de vos passions.","color":"#99a9ff","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"whatsapp","name":"WhatsApp","url":"https://web.whatsapp.com/","description":"Vos conversations depuis WhatsApp dans le navigateur.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"pinterest","name":"Pinterest","url":"https://www.pinterest.com/","description":"Idées, inspirations et collections de visuels.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"tumblr","name":"Tumblr","url":"https://www.tumblr.com/","description":"Blogs, publications et communautés créatives.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"discord","name":"Discord","url":"https://discord.com/channels/@me","description":"Vos serveurs et conversations dans le client web.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"telegram","name":"Telegram","url":"https://web.telegram.org/","description":"Accédez à vos conversations dans le client web.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"kick","name":"Kick","url":"https://kick.com/","description":"Diffusions en direct et communautés de créateurs.","color":"#99a9ff","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"wechat","name":"WeChat","url":"https://web.wechat.com/","description":"Retrouvez vos messages avec votre compte WeChat.","color":"#99a9ff","tag":"Compte requis","categoryIds":["social"],"defaultIncluded":false},
        {"serviceId":"bluesky","name":"Bluesky","url":"https://bsky.app/","description":"Publications et fils de discussion de votre réseau.","color":"#99a9ff","categoryIds":["social"],"defaultIncluded":false},
      ],
    },
    {
      id: "news",
      label: "Actualités",
      description: "L’essentiel de l’information et de la mobilité.",
      shortcuts: [
        {"serviceId":"cnews","name":"CNEWS","url":"https://www.cnews.fr/","description":"Les dernières informations et le direct de CNEWS.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"euronews","name":"Euronews","url":"https://fr.euronews.com/live","description":"Le direct de l’actualité européenne en français.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"afp","name":"AFP","url":"https://www.afp.com/","description":"Le site de l’agence et ses informations publiques.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"bfm-tv","name":"BFM TV","url":"https://www.bfmtv.com/","description":"Actualités françaises et internationales en continu.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"20-minutes","name":"20 Minutes","url":"https://www.20minutes.fr/","description":"Les dernières nouvelles et sujets de société.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"le-monde","name":"Le Monde","url":"https://www.lemonde.fr/","description":"Actualité, enquêtes et analyses du quotidien.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"le-figaro","name":"Le Figaro","url":"https://www.lefigaro.fr/","description":"Actualité, économie et analyses du quotidien.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"france-24","name":"France 24","url":"https://www.france24.com/fr/","description":"Actualité internationale et reportages en français.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"reuters","name":"Reuters","url":"https://www.reuters.com/world/","description":"Actualité mondiale et reportages en langue anglaise.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"bbc-news","name":"BBC News","url":"https://www.bbc.com/news","description":"Actualité internationale et reportages de la BBC.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"the-guardian","name":"The Guardian","url":"https://www.theguardian.com/","description":"Actualités et analyses du quotidien britannique.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"liberation","name":"Libération","url":"https://www.liberation.fr/","description":"Actualité, enquêtes et regards sur la société.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"l-express","name":"L'Express","url":"https://www.lexpress.fr/","description":"Actualité, analyses et débats de l’hebdomadaire.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"franceinfo","name":"franceinfo","url":"https://www.franceinfo.fr/","description":"L’actualité en continu du service public français.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"the-new-york-times","name":"The New York Times","url":"https://www.nytimes.com/","description":"Actualité et enquêtes du quotidien américain.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"washington-post","name":"Washington Post","url":"https://www.washingtonpost.com/","description":"Actualité américaine et enquêtes du quotidien.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"cnn","name":"CNN","url":"https://edition.cnn.com/","description":"Actualité internationale et vidéos en langue anglaise.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"al-jazeera","name":"Al Jazeera","url":"https://www.aljazeera.com/","description":"Actualité et reportages internationaux en anglais.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"mediapart","name":"Mediapart","url":"https://www.mediapart.fr/","description":"Enquêtes et journalisme indépendant par abonnement.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"rtbf-info","name":"RTBF Info","url":"https://www.rtbf.be/info","description":"Actualité belge et internationale en français.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"rt-news","name":"RT News","url":"https://www.rt.com/","description":"Actualité de RT, avec un accès variable selon la région.","color":"#e296be","tag":"Selon région","categoryIds":["news"]},
        {"serviceId":"automobile-propre","name":"Automobile Propre","url":"https://www.automobile-propre.com/","description":"Actualités et essais autour de la mobilité électrique.","color":"#e296be","categoryIds":["news"]},
        {"serviceId":"techmeme","name":"Techmeme","url":"https://www.techmeme.com/","description":"Les principaux titres de l’actualité technologique en anglais.","color":"#e296be","categoryIds":["news"]},
      ],
    },
    {
      id: "weather",
      label: "Météo",
      description: "Anticipez le temps sur votre prochain trajet.",
      shortcuts: [
        {"serviceId":"ventusky","name":"Ventusky","url":"https://www.ventusky.com/","description":"Cartes animées des températures, pluies et vents.","color":"#e8c96a","categoryIds":["weather"]},
        {"serviceId":"windy","name":"Windy","url":"https://www.windy.com/","description":"Visualisez les prévisions sur une carte interactive.","color":"#e8c96a","categoryIds":["weather"]},
        {"serviceId":"weather-com","name":"Weather.com","url":"https://weather.com/","description":"Prévisions locales et informations météorologiques.","color":"#e8c96a","categoryIds":["weather"]},
        {"serviceId":"la-chaine-meteo","name":"La Chaîne Météo","url":"https://www.lachainemeteo.com/","description":"Prévisions météo en France et dans le monde.","color":"#e8c96a","categoryIds":["weather"]},
        {"serviceId":"meteo-france","name":"Météo-France","url":"https://meteofrance.com/","description":"Prévisions locales du service météorologique français.","color":"#e8c96a","categoryIds":["weather"]},
        {"serviceId":"accuweather","name":"AccuWeather","url":"https://www.accuweather.com/","description":"Prévisions météo locales et tendances à venir.","color":"#e8c96a","categoryIds":["weather"]},
        {"serviceId":"vigilance-meteo","name":"Vigilance météo","url":"https://vigilance.meteofrance.fr/fr","description":"Consultez la carte officielle de vigilance Météo-France.","color":"#e8c96a","categoryIds":["weather"]},
        {"serviceId":"zoom-earth","name":"Zoom Earth","url":"https://zoom.earth/","description":"Images satellite, radar météo et suivi des tempêtes.","color":"#e8c96a","categoryIds":["weather"]},
        {"serviceId":"lightningmaps","name":"LightningMaps","url":"https://www.lightningmaps.org/","description":"Carte des impacts de foudre détectés en temps réel.","color":"#e8c96a","categoryIds":["weather"]},
      ],
    },
    {
      id: "productivity",
      label: "Outils & services",
      description: "Vos services utiles réunis au même endroit.",
      shortcuts: [
        {"serviceId":"google-drive","name":"Google Drive","url":"https://drive.google.com/","description":"Consultez vos fichiers et dossiers dans le cloud.","color":"#91bdad","tag":"Compte requis","categoryIds":["productivity"],"defaultIncluded":false},
        {"serviceId":"gmail","name":"Gmail","url":"https://mail.google.com/","description":"Retrouvez vos e-mails dans la messagerie Google.","color":"#91bdad","tag":"Compte requis","categoryIds":["productivity"],"defaultIncluded":false},
        {"serviceId":"google-agenda","name":"Google Agenda","url":"https://calendar.google.com/","description":"Votre agenda, vos rendez-vous et vos événements.","color":"#91bdad","tag":"Compte requis","categoryIds":["productivity"],"defaultIncluded":false},
        {"serviceId":"github","name":"GitHub","url":"https://github.com/","description":"Consultez vos projets, dépôts et discussions de code.","color":"#91bdad","categoryIds":["productivity"],"defaultIncluded":false},
        {"serviceId":"notion","name":"Notion","url":"https://www.notion.com/","description":"Vos notes, documents et espaces de travail partagés.","color":"#91bdad","tag":"Compte requis","categoryIds":["productivity"],"defaultIncluded":false},
        {"serviceId":"google-docs","name":"Google Docs","url":"https://docs.google.com/","description":"Consultez et modifiez vos documents en ligne.","color":"#91bdad","tag":"Compte requis","categoryIds":["productivity"],"defaultIncluded":false},
        {"serviceId":"outlook","name":"Outlook","url":"https://outlook.live.com/mail/","description":"Vos e-mails et votre agenda dans le navigateur.","color":"#91bdad","tag":"Compte requis","categoryIds":["productivity"],"defaultIncluded":false},
        {"serviceId":"onedrive","name":"OneDrive","url":"https://onedrive.live.com/","description":"Accédez aux services de stockage cloud Microsoft.","color":"#91bdad","tag":"Compte requis","categoryIds":["productivity"],"defaultIncluded":false},
        {"serviceId":"deepl","name":"DeepL","url":"https://www.deepl.com/fr/translator","description":"Traduisez rapidement vos textes dans le navigateur.","color":"#91bdad","categoryIds":["productivity"]},
        {"serviceId":"wikipedia","name":"Wikipédia","url":"https://fr.wikipedia.org/","description":"L’encyclopédie collaborative en langue française.","color":"#91bdad","categoryIds":["productivity"]},
        {"serviceId":"fast-com","name":"FAST.com","url":"https://fast.com/","description":"Mesurez le débit de votre connexion Internet.","color":"#91bdad","categoryIds":["productivity"]},
      ],
    },
  ],
  replacements: [
    {"from":"https://www.max.com/","to":"https://www.hbomax.com/","name":"HBO Max","legacyName":"Max"},
    {"from":"https://replay.gulli.fr/Direct","to":"https://www.m6.fr/gulli/direct","name":"Gulli","legacyName":"Replay Gulli"},
    {"from":"https://www.deezer.com/en/channels/explore/","to":"https://www.deezer.com/fr/channels/explore","name":"Deezer","legacyName":"Deezer"},
    {"from":"https://www.soundcloud.com/","to":"https://soundcloud.com/","name":"SoundCloud","legacyName":"SoundCloud"},
    {"from":"https://tidal.com/","to":"https://listen.tidal.com/","name":"TIDAL","legacyName":"Tidal"},
    {"from":"https://www.qobuz.com/","to":"https://play.qobuz.com/","name":"Qobuz","legacyName":"Qobuz"},
    {"from":"https://www.6play.fr/","to":"https://www.m6.fr/","name":"M6+","legacyName":"6play"},
    {"from":"https://www.tv5monde.com/","to":"https://www.tv5mondeplus.com/fr","name":"TV5MONDEplus","legacyName":"TV5Monde"},
    {"from":"https://www.rtbf.be/auvio/direct","to":"https://auvio.rtbf.be/direct","name":"RTBF Auvio","legacyName":"RTBFAuvio"},
    {"from":"https://pluto.tv/live-tv","to":"https://pluto.tv/","name":"Pluto TV","legacyName":"PlutoTV"},
    {"from":"https://www.tesla.com/findus/location/supercharger","to":"https://www.tesla.com/fr_fr/findus","name":"Tesla Superchargeurs","legacyName":"Tesla Superchargers"},
    {"from":"https://fr.chargemap.com/map","to":"https://chargemap.com/fr-fr/map","name":"Chargemap","legacyName":"ChargeMap"},
    {"from":"https://play.geforcenow.com/mall/#/layout/games","to":"https://play.geforcenow.com/","name":"GeForce NOW","legacyName":"GForceNow"},
    {"from":"https://www.crazygames.fr/","to":"https://www.crazygames.com/fr/","name":"CrazyGames","legacyName":"Crazy Games"},
    {"from":"https://www.waze.com/","to":"https://www.waze.com/live-map/?locale=fr","name":"Waze","legacyName":"Waze"},
    {"from":"https://beta.maps.apple.com/","to":"https://maps.apple.com/","name":"Apple Plans","legacyName":"Apple Maps"},
    {"from":"https://www.tomtom.com/en_gb/navigation/","to":"https://plan.tomtom.com/","name":"TomTom Plan","legacyName":"TomTom GO"},
    {"from":"https://www.x.com/","to":"https://x.com/","name":"X","legacyName":"X"},
    {"from":"https://www.snapchat.com/","to":"https://web.snapchat.com/","name":"Snapchat","legacyName":"Snapchat"},
    {"from":"https://www.francetvinfo.fr/","to":"https://www.franceinfo.fr/","name":"franceinfo","legacyName":"FranceInfo"},
    {"from":"https://www.notion.so/","to":"https://www.notion.com/","name":"Notion","legacyName":"Notion"},
    {"from":"https://outlook.live.com/","to":"https://outlook.live.com/mail/","name":"Outlook","legacyName":"Outlook"},
    {"from":"https://pluto.tv/fr/","to":"https://pluto.tv/","name":"Pluto TV","legacyName":"Pluto TV"},
    {"from":"https://pluto.tv/fr/watch/live-tv/","to":"https://pluto.tv/","name":"Pluto TV","legacyName":"Pluto TV"},
  ],
};
