/**
 * Catalogue éditorial EvPortal — septembre 2026.
 * Vérifications, limites et sources : docs/LIENS.md.
 * Couleurs des monogrammes utilisés lorsque le logo local est indisponible.
 * Un lien accessible ne garantit pas la lecture sur un navigateur embarqué.
 */
window.EV_CATALOG = {
  version: "2026-09",
  categories: [
    {
      id: "cinema",
      label: "Cinéma & vidéo",
      description: "Films, séries et vidéos pour votre pause.",
      shortcuts: [
        {"name": "Netflix", "url": "https://www.netflix.com/", "description": "Films, séries et documentaires à la demande.", "color": "#ff6b7a", "tag": "Compte requis"},
        {"name": "Plex", "url": "https://app.plex.tv/", "description": "Votre médiathèque et des programmes en streaming.", "color": "#f3c45b"},
        {"name": "Prime Video", "url": "https://www.primevideo.com/", "description": "Films, séries et créations Amazon à la demande.", "color": "#58c6f0", "tag": "Compte requis"},
        {"name": "Disney+", "url": "https://www.disneyplus.com/", "description": "Films et séries Disney, Pixar, Marvel et plus.", "color": "#929dff", "tag": "Compte requis"},
        {"name": "HBO Max", "url": "https://www.hbomax.com/", "description": "Films, séries HBO et documentaires à la demande.", "color": "#b79aff", "tag": "Compte requis"},
        {"name": "Paramount+", "url": "https://www.paramountplus.com/fr/", "description": "Films, séries et créations originales Paramount.", "color": "#82a9ff", "tag": "Compte requis"},
        {"name": "Pluto TV", "url": "https://pluto.tv/fr/", "description": "Chaînes en direct et programmes à la demande.", "color": "#f2d266"},
        {"name": "Crave", "url": "https://www.crave.ca/fr", "description": "Films et séries pour les spectateurs au Canada.", "color": "#ec678e", "tag": "Selon région"},
        {"name": "Starz", "url": "https://www.starz.com/", "description": "Séries originales et cinéma du catalogue STARZ.", "color": "#ec678e", "tag": "Selon région"},
        {"name": "DAZN", "url": "https://www.dazn.com/", "description": "Retransmissions et programmes consacrés au sport.", "color": "#ec678e", "tag": "Compte requis"},
        {"name": "CANAL+", "url": "https://www.canalplus.com/", "description": "Cinéma, séries, sport et chaînes du groupe CANAL+.", "color": "#d4dce6", "tag": "Compte requis"},
        {"name": "Apple TV", "url": "https://tv.apple.com/fr", "description": "Séries originales et films du catalogue Apple TV.", "color": "#cbd3df", "tag": "Compte requis"},
        {"name": "YouTube", "url": "https://www.youtube.com/", "description": "Vidéos, chaînes et créations à découvrir en ligne.", "color": "#ff777b"},
        {"name": "Gulli", "url": "https://www.m6.fr/gulli/direct", "description": "Accès au direct Gulli sur la plateforme M6+.", "color": "#ec678e"},
        {"name": "Rakuten TV", "url": "https://www.rakuten.tv/fr/gardens/free", "description": "Une sélection de films en streaming avec publicité.", "color": "#ec678e"},
      ],
    },
    {
      id: "music",
      label: "Musique & radio",
      description: "Vos morceaux, radios et podcasts préférés.",
      shortcuts: [
        {"name": "Apple Music", "url": "https://music.apple.com/", "description": "Votre musique et vos playlists dans le navigateur.", "color": "#fa80a1", "tag": "Compte requis"},
        {"name": "Spotify", "url": "https://open.spotify.com/", "description": "Musique, playlists et podcasts dans le lecteur web.", "color": "#65db91", "tag": "Compte requis"},
        {"name": "Deezer", "url": "https://www.deezer.com/fr/channels/explore", "description": "Musique et playlists depuis la version française.", "color": "#bd8aff", "tag": "Compte requis"},
        {"name": "SoundCloud", "url": "https://soundcloud.com/", "description": "Morceaux, artistes indépendants et découvertes audio.", "color": "#ffad76"},
        {"name": "YouTube Music", "url": "https://music.youtube.com/", "description": "Musique, clips et playlists du catalogue YouTube.", "color": "#ff878e"},
        {"name": "TIDAL", "url": "https://listen.tidal.com/", "description": "Le lecteur web pour votre bibliothèque musicale.", "color": "#a48cff", "tag": "Compte requis"},
        {"name": "Qobuz", "url": "https://play.qobuz.com/", "description": "Écoutez vos albums depuis le lecteur web Qobuz.", "color": "#a48cff", "tag": "Compte requis"},
        {"name": "Bandcamp", "url": "https://bandcamp.com/", "description": "Albums et découvertes des artistes indépendants.", "color": "#a48cff"},
        {"name": "AccuRadio", "url": "https://www.accuradio.com/", "description": "Radios musicales classées par genres et ambiances.", "color": "#a48cff"},
        {"name": "iHeartRadio", "url": "https://www.iheart.com/", "description": "Radios et podcasts, selon votre zone géographique.", "color": "#a48cff", "tag": "Selon région"},
        {"name": "Mixcloud", "url": "https://www.mixcloud.com/", "description": "Mix, émissions musicales et créations de DJ.", "color": "#a48cff"},
        {"name": "LiveOne", "url": "https://www.liveone.com/", "description": "Radios, musique et programmes audio en streaming.", "color": "#a48cff"},
        {"name": "IDAGIO", "url": "https://www.idagio.com/", "description": "Une bibliothèque dédiée à la musique classique.", "color": "#a48cff", "tag": "Compte requis"},
        {"name": "TuneIn", "url": "https://tunein.com/radio/home/", "description": "Radios en direct, actualité et podcasts du monde.", "color": "#a48cff"},
        {"name": "Radio France", "url": "https://www.radiofrance.fr/", "description": "Radios publiques, émissions et podcasts en français.", "color": "#a48cff"},
        {"name": "FIP", "url": "https://www.radiofrance.fr/fip", "description": "Une radio musicale éclectique et ses webradios.", "color": "#f18fc5"},
        {"name": "France Inter", "url": "https://www.radiofrance.fr/franceinter", "description": "Écoutez le direct et les podcasts de France Inter.", "color": "#a48cff"},
        {"name": "France Culture", "url": "https://www.radiofrance.fr/franceculture", "description": "Émissions, documentaires et podcasts culturels.", "color": "#a48cff"},
        {"name": "Radio Garden", "url": "https://radio.garden/", "description": "Explorez les radios du monde sur un globe interactif.", "color": "#a48cff", "tag": "Selon région"},
      ],
    },
    {
      id: "tv",
      label: "Télévision",
      description: "Les directs et replays à portée de main.",
      shortcuts: [
        {"name": "Molotov", "url": "https://www.molotov.tv/", "description": "Télévision et replay selon les offres disponibles.", "color": "#61b8ff", "tag": "Compte requis"},
        {"name": "france.tv", "url": "https://www.france.tv/", "description": "Les directs et replays de France Télévisions.", "color": "#61b8ff", "tag": "Compte requis"},
        {"name": "TF1+", "url": "https://www.tf1.fr/", "description": "Émissions, séries et direct sur la plateforme TF1+.", "color": "#61b8ff", "tag": "Compte requis"},
        {"name": "M6+", "url": "https://www.m6.fr/", "description": "Émissions, séries et replays des chaînes du groupe M6.", "color": "#61b8ff", "tag": "Compte requis"},
        {"name": "ARTE", "url": "https://www.arte.tv/fr/", "description": "Documentaires, cinéma et programmes culturels.", "color": "#ff966b"},
        {"name": "TV5MONDEplus", "url": "https://www.tv5mondeplus.com/fr", "description": "Films, séries et documentaires de la francophonie.", "color": "#61b8ff"},
        {"name": "RTBF Auvio", "url": "https://auvio.rtbf.be/direct", "description": "Les directs et programmes de la télévision belge.", "color": "#61b8ff", "tag": "Selon région"},
        {"name": "Pluto TV", "url": "https://pluto.tv/fr/watch/live-tv/", "description": "Chaînes en direct et programmes à la demande.", "color": "#f2d266"},
        {"name": "CANAL+", "url": "https://www.canalplus.com/", "description": "Les chaînes et replays de votre offre CANAL+.", "color": "#d4dce6", "tag": "Compte requis"},
      ],
    },
    {
      id: "charging",
      label: "Recharge",
      description: "Trouvez une borne et préparez vos étapes.",
      shortcuts: [
        {"name": "ChargePoint", "url": "https://driver.chargepoint.com/", "description": "Carte des bornes du réseau et informations utiles.", "color": "#efa16e"},
        {"name": "ABRP", "url": "https://abetterrouteplanner.com/", "description": "Planifiez vos trajets et vos arrêts de recharge.", "color": "#77c3ef"},
        {"name": "PlugShare", "url": "https://www.plugshare.com/", "description": "Carte des bornes et retours de la communauté VE.", "color": "#71dcab"},
        {"name": "Tesla Superchargeurs", "url": "https://www.tesla.com/fr_fr/findus", "description": "Localisez les stations Superchargeurs de Tesla.", "color": "#ff7b83"},
        {"name": "Chargemap", "url": "https://chargemap.com/fr-fr/map", "description": "Carte des bornes, connecteurs et avis des conducteurs.", "color": "#63cbb9"},
        {"name": "Chargeprice", "url": "https://fr.chargeprice.app/", "description": "Comparez les tarifs de recharge selon vos cartes.", "color": "#71dcab"},
        {"name": "IONITY", "url": "https://www.ionity.eu/network", "description": "Carte des stations du réseau de recharge européen.", "color": "#da8fcd"},
        {"name": "Electra", "url": "https://stations.go-electra.com/fr", "description": "Trouvez les stations et informations du réseau Electra.", "color": "#71dcab"},
        {"name": "Fastned", "url": "https://www.fastnedcharging.com/fr/emplacements", "description": "Carte des stations de recharge du réseau Fastned.", "color": "#f3cf5f"},
        {"name": "Freshmile", "url": "https://charge.freshmile.com/map", "description": "Repérez les bornes accessibles avec le réseau Freshmile.", "color": "#71dcab"},
        {"name": "ChargeFinder", "url": "https://chargefinder.com/fr", "description": "Carte des bornes et informations sur leur disponibilité.", "color": "#71dcab"},
      ],
    },
    {
      id: "games",
      label: "Jeux",
      description: "Une pause ludique, directement sur le web.",
      shortcuts: [
        {"name": "GeForce NOW", "url": "https://play.geforcenow.com/", "description": "Accédez à vos jeux PC via le service cloud NVIDIA.", "color": "#b2d86b", "tag": "Compte requis"},
        {"name": "AirConsole", "url": "https://www.airconsole.com/", "description": "Jeux multijoueurs avec un téléphone comme manette.", "color": "#eeae63", "tag": "Téléphone requis"},
        {"name": "2048", "url": "https://jeu2048.fr/", "description": "Assemblez les tuiles pour atteindre le nombre 2048.", "color": "#eeae63"},
        {"name": "Solitaire", "url": "https://solitaire.com/", "description": "Une partie de cartes à lancer dans le navigateur.", "color": "#eeae63"},
        {"name": "Démineur", "url": "https://minesweeperonline.com/", "description": "Retrouvez les mines avec logique et déduction.", "color": "#eeae63"},
        {"name": "Snake", "url": "https://playsnake.org/", "description": "Le jeu du serpent pour une courte pause ludique.", "color": "#eeae63"},
        {"name": "Chess.com", "url": "https://www.chess.com/", "description": "Parties, exercices et apprentissage des échecs.", "color": "#eeae63"},
        {"name": "CrazyGames", "url": "https://www.crazygames.com/fr/", "description": "Une sélection de jeux à lancer dans le navigateur.", "color": "#eeae63"},
        {"name": "Jeux.fr", "url": "https://www.jeux.fr/", "description": "Jeux de réflexion, de cartes et petites aventures.", "color": "#eeae63"},
        {"name": "1001 Jeux", "url": "https://www.1001jeux.fr/", "description": "Des jeux de navigateur classés par catégories.", "color": "#eeae63"},
        {"name": "Poki", "url": "https://poki.com/fr", "description": "Jeux de réflexion, de course et aventures en ligne.", "color": "#eeae63"},
        {"name": "Jeux-Gratuits.com", "url": "https://www.jeux-gratuits.com/", "description": "Jeux de cartes, logique et divertissements en ligne.", "color": "#eeae63"},
        {"name": "PlayHop", "url": "https://playhop.com/fr", "description": "Un catalogue de jeux à découvrir dans le navigateur.", "color": "#eeae63"},
        {"name": "Lichess", "url": "https://lichess.org/fr", "description": "Échecs en ligne, entraînement et défis de logique.", "color": "#eeae63", "tag": "Sans publicité"},
        {"name": "Sudoku", "url": "https://sudoku.com/fr", "description": "Grilles de sudoku en français, du facile à l’expert.", "color": "#eeae63"},
      ],
    },
    {
      id: "navigation",
      label: "Navigation & trafic",
      description: "Préparez la route et consultez le trafic.",
      shortcuts: [
        {"name": "Google Maps", "url": "https://maps.google.com/", "description": "Recherchez un lieu et préparez votre prochain trajet.", "color": "#5ac9db"},
        {"name": "Waze", "url": "https://www.waze.com/live-map/?locale=fr", "description": "Carte du trafic et préparation de vos itinéraires.", "color": "#5ac9db"},
        {"name": "Apple Plans", "url": "https://maps.apple.com/", "description": "Lieux, cartes et itinéraires dans Apple Plans web.", "color": "#5ac9db"},
        {"name": "HERE WeGo", "url": "https://wego.here.com/", "description": "Cartes et calcul d’itinéraires pour vos déplacements.", "color": "#5ac9db"},
        {"name": "OpenStreetMap", "url": "https://www.openstreetmap.org/", "description": "La carte collaborative pour explorer les environs.", "color": "#5ac9db"},
        {"name": "MapQuest", "url": "https://www.mapquest.com/", "description": "Cartes et itinéraires, notamment en Amérique du Nord.", "color": "#5ac9db"},
        {"name": "Bing Maps", "url": "https://www.bing.com/maps", "description": "Recherchez des lieux et consultez les cartes Bing.", "color": "#5ac9db"},
        {"name": "ABRP", "url": "https://abetterrouteplanner.com/", "description": "Préparez votre trajet avec des étapes de recharge.", "color": "#77c3ef"},
        {"name": "TomTom Plan", "url": "https://plan.tomtom.com/", "description": "Préparez vos parcours dans le planificateur web.", "color": "#5ac9db"},
        {"name": "Infotrafic", "url": "https://www.infotrafic.com/", "description": "Informations de circulation et état du réseau routier.", "color": "#5ac9db"},
        {"name": "Bison Futé", "url": "https://www.bison-fute.gouv.fr/zoommaintenant.html", "description": "Carte officielle du trafic et des événements routiers.", "color": "#5ac9db"},
        {"name": "Sytadin", "url": "https://www.sytadin.fr/", "description": "Trafic et temps de parcours des routes d’Île-de-France.", "color": "#5ac9db"},
      ],
    },
    {
      id: "social",
      label: "Réseaux sociaux",
      description: "Retrouvez vos proches et vos communautés.",
      shortcuts: [
        {"name": "Facebook", "url": "https://www.facebook.com/", "description": "Actualités de vos proches, groupes et communautés.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "X", "url": "https://x.com/", "description": "Publications et conversations sur vos sujets suivis.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "Instagram", "url": "https://www.instagram.com/", "description": "Photos, vidéos et nouvelles de vos comptes suivis.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "LinkedIn", "url": "https://www.linkedin.com/", "description": "Votre réseau professionnel et ses publications.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "Snapchat", "url": "https://web.snapchat.com/", "description": "Vos conversations dans la version web de Snapchat.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "TikTok", "url": "https://www.tiktok.com/", "description": "Vidéos courtes et créateurs à découvrir en ligne.", "color": "#99a9ff"},
        {"name": "Reddit", "url": "https://www.reddit.com/", "description": "Discussions et communautés autour de vos passions.", "color": "#99a9ff"},
        {"name": "WhatsApp", "url": "https://web.whatsapp.com/", "description": "Vos conversations depuis WhatsApp dans le navigateur.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "Pinterest", "url": "https://www.pinterest.com/", "description": "Idées, inspirations et collections de visuels.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "Tumblr", "url": "https://www.tumblr.com/", "description": "Blogs, publications et communautés créatives.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "Discord", "url": "https://discord.com/channels/@me", "description": "Vos serveurs et conversations dans le client web.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "Telegram", "url": "https://web.telegram.org/", "description": "Accédez à vos conversations dans le client web.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "Kick", "url": "https://kick.com/", "description": "Diffusions en direct et communautés de créateurs.", "color": "#99a9ff"},
        {"name": "WeChat", "url": "https://web.wechat.com/", "description": "Retrouvez vos messages avec votre compte WeChat.", "color": "#99a9ff", "tag": "Compte requis"},
        {"name": "Bluesky", "url": "https://bsky.app/", "description": "Publications et fils de discussion de votre réseau.", "color": "#99a9ff"},
      ],
    },
    {
      id: "news",
      label: "Actualités",
      description: "L’essentiel de l’information et de la mobilité.",
      shortcuts: [
        {"name": "CNEWS", "url": "https://www.cnews.fr/", "description": "Les dernières informations et le direct de CNEWS.", "color": "#e296be"},
        {"name": "Euronews", "url": "https://fr.euronews.com/live", "description": "Le direct de l’actualité européenne en français.", "color": "#e296be"},
        {"name": "AFP", "url": "https://www.afp.com/", "description": "Le site de l’agence et ses informations publiques.", "color": "#e296be"},
        {"name": "BFM TV", "url": "https://www.bfmtv.com/", "description": "Actualités françaises et internationales en continu.", "color": "#e296be"},
        {"name": "20 Minutes", "url": "https://www.20minutes.fr/", "description": "Les dernières nouvelles et sujets de société.", "color": "#e296be"},
        {"name": "Le Monde", "url": "https://www.lemonde.fr/", "description": "Actualité, enquêtes et analyses du quotidien.", "color": "#e296be"},
        {"name": "Le Figaro", "url": "https://www.lefigaro.fr/", "description": "Actualité, économie et analyses du quotidien.", "color": "#e296be"},
        {"name": "France 24", "url": "https://www.france24.com/fr/", "description": "Actualité internationale et reportages en français.", "color": "#e296be"},
        {"name": "Reuters", "url": "https://www.reuters.com/world/", "description": "Actualité mondiale et reportages en langue anglaise.", "color": "#e296be"},
        {"name": "BBC News", "url": "https://www.bbc.com/news", "description": "Actualité internationale et reportages de la BBC.", "color": "#e296be"},
        {"name": "The Guardian", "url": "https://www.theguardian.com/", "description": "Actualités et analyses du quotidien britannique.", "color": "#e296be"},
        {"name": "Libération", "url": "https://www.liberation.fr/", "description": "Actualité, enquêtes et regards sur la société.", "color": "#e296be"},
        {"name": "L'Express", "url": "https://www.lexpress.fr/", "description": "Actualité, analyses et débats de l’hebdomadaire.", "color": "#e296be"},
        {"name": "franceinfo", "url": "https://www.franceinfo.fr/", "description": "L’actualité en continu du service public français.", "color": "#e296be"},
        {"name": "The New York Times", "url": "https://www.nytimes.com/", "description": "Actualité et enquêtes du quotidien américain.", "color": "#e296be"},
        {"name": "Washington Post", "url": "https://www.washingtonpost.com/", "description": "Actualité américaine et enquêtes du quotidien.", "color": "#e296be"},
        {"name": "CNN", "url": "https://edition.cnn.com/", "description": "Actualité internationale et vidéos en langue anglaise.", "color": "#e296be"},
        {"name": "Al Jazeera", "url": "https://www.aljazeera.com/", "description": "Actualité et reportages internationaux en anglais.", "color": "#e296be"},
        {"name": "Mediapart", "url": "https://www.mediapart.fr/", "description": "Enquêtes et journalisme indépendant par abonnement.", "color": "#e296be"},
        {"name": "RTBF Info", "url": "https://www.rtbf.be/info", "description": "Actualité belge et internationale en français.", "color": "#e296be"},
        {"name": "RT News", "url": "https://www.rt.com/", "description": "Actualité de RT, avec un accès variable selon la région.", "color": "#e296be", "tag": "Selon région"},
        {"name": "Automobile Propre", "url": "https://www.automobile-propre.com/", "description": "Actualités et essais autour de la mobilité électrique.", "color": "#e296be"},
      ],
    },
    {
      id: "weather",
      label: "Météo",
      description: "Anticipez le temps sur votre prochain trajet.",
      shortcuts: [
        {"name": "Ventusky", "url": "https://www.ventusky.com/", "description": "Cartes animées des températures, pluies et vents.", "color": "#e8c96a"},
        {"name": "Windy", "url": "https://www.windy.com/", "description": "Visualisez les prévisions sur une carte interactive.", "color": "#e8c96a"},
        {"name": "Weather.com", "url": "https://weather.com/", "description": "Prévisions locales et informations météorologiques.", "color": "#e8c96a"},
        {"name": "La Chaîne Météo", "url": "https://www.lachainemeteo.com/", "description": "Prévisions météo en France et dans le monde.", "color": "#e8c96a"},
        {"name": "Météo-France", "url": "https://meteofrance.com/", "description": "Prévisions locales du service météorologique français.", "color": "#e8c96a"},
        {"name": "AccuWeather", "url": "https://www.accuweather.com/", "description": "Prévisions météo locales et tendances à venir.", "color": "#e8c96a"},
        {"name": "Vigilance météo", "url": "https://vigilance.meteofrance.fr/fr", "description": "Consultez la carte officielle de vigilance Météo-France.", "color": "#e8c96a"},
      ],
    },
    {
      id: "productivity",
      label: "Outils & services",
      description: "Vos services utiles réunis au même endroit.",
      shortcuts: [
        {"name": "Google Drive", "url": "https://drive.google.com/", "description": "Consultez vos fichiers et dossiers dans le cloud.", "color": "#91bdad", "tag": "Compte requis"},
        {"name": "Gmail", "url": "https://mail.google.com/", "description": "Retrouvez vos e-mails dans la messagerie Google.", "color": "#91bdad", "tag": "Compte requis"},
        {"name": "Google Agenda", "url": "https://calendar.google.com/", "description": "Votre agenda, vos rendez-vous et vos événements.", "color": "#91bdad", "tag": "Compte requis"},
        {"name": "GitHub", "url": "https://github.com/", "description": "Consultez vos projets, dépôts et discussions de code.", "color": "#91bdad"},
        {"name": "Notion", "url": "https://www.notion.com/", "description": "Vos notes, documents et espaces de travail partagés.", "color": "#91bdad", "tag": "Compte requis"},
        {"name": "Google Docs", "url": "https://docs.google.com/", "description": "Consultez et modifiez vos documents en ligne.", "color": "#91bdad", "tag": "Compte requis"},
        {"name": "Outlook", "url": "https://outlook.live.com/mail/", "description": "Vos e-mails et votre agenda dans le navigateur.", "color": "#91bdad", "tag": "Compte requis"},
        {"name": "OneDrive", "url": "https://onedrive.live.com/", "description": "Accédez aux services de stockage cloud Microsoft.", "color": "#91bdad", "tag": "Compte requis"},
        {"name": "DeepL", "url": "https://www.deepl.com/fr/translator", "description": "Traduisez rapidement vos textes dans le navigateur.", "color": "#91bdad"},
        {"name": "Wikipédia", "url": "https://fr.wikipedia.org/", "description": "L’encyclopédie collaborative en langue française.", "color": "#91bdad"},
      ],
    },
  ],
  replacements: [
    {"from": "https://www.max.com/", "to": "https://www.hbomax.com/", "name": "HBO Max", "legacyName": "Max"},
    {"from": "https://replay.gulli.fr/Direct", "to": "https://www.m6.fr/gulli/direct", "name": "Gulli", "legacyName": "Replay Gulli"},
    {"from": "https://www.deezer.com/en/channels/explore/", "to": "https://www.deezer.com/fr/channels/explore", "name": "Deezer", "legacyName": "Deezer"},
    {"from": "https://www.soundcloud.com/", "to": "https://soundcloud.com/", "name": "SoundCloud", "legacyName": "SoundCloud"},
    {"from": "https://tidal.com/", "to": "https://listen.tidal.com/", "name": "TIDAL", "legacyName": "Tidal"},
    {"from": "https://www.qobuz.com/", "to": "https://play.qobuz.com/", "name": "Qobuz", "legacyName": "Qobuz"},
    {"from": "https://www.6play.fr/", "to": "https://www.m6.fr/", "name": "M6+", "legacyName": "6play"},
    {"from": "https://www.tv5monde.com/", "to": "https://www.tv5mondeplus.com/fr", "name": "TV5MONDEplus", "legacyName": "TV5Monde"},
    {"from": "https://www.rtbf.be/auvio/direct", "to": "https://auvio.rtbf.be/direct", "name": "RTBF Auvio", "legacyName": "RTBFAuvio"},
    {"from": "https://pluto.tv/live-tv", "to": "https://pluto.tv/fr/watch/live-tv/", "name": "Pluto TV", "legacyName": "PlutoTV"},
    {"from": "https://www.tesla.com/findus/location/supercharger", "to": "https://www.tesla.com/fr_fr/findus", "name": "Tesla Superchargeurs", "legacyName": "Tesla Superchargers"},
    {"from": "https://fr.chargemap.com/map", "to": "https://chargemap.com/fr-fr/map", "name": "Chargemap", "legacyName": "ChargeMap"},
    {"from": "https://play.geforcenow.com/mall/#/layout/games", "to": "https://play.geforcenow.com/", "name": "GeForce NOW", "legacyName": "GForceNow"},
    {"from": "https://www.crazygames.fr/", "to": "https://www.crazygames.com/fr/", "name": "CrazyGames", "legacyName": "Crazy Games"},
    {"from": "https://www.waze.com/", "to": "https://www.waze.com/live-map/?locale=fr", "name": "Waze", "legacyName": "Waze"},
    {"from": "https://beta.maps.apple.com/", "to": "https://maps.apple.com/", "name": "Apple Plans", "legacyName": "Apple Maps"},
    {"from": "https://www.tomtom.com/en_gb/navigation/", "to": "https://plan.tomtom.com/", "name": "TomTom Plan", "legacyName": "TomTom GO"},
    {"from": "https://www.x.com/", "to": "https://x.com/", "name": "X", "legacyName": "X"},
    {"from": "https://www.snapchat.com/", "to": "https://web.snapchat.com/", "name": "Snapchat", "legacyName": "Snapchat"},
    {"from": "https://www.francetvinfo.fr/", "to": "https://www.franceinfo.fr/", "name": "franceinfo", "legacyName": "FranceInfo"},
    {"from": "https://www.notion.so/", "to": "https://www.notion.com/", "name": "Notion", "legacyName": "Notion"},
    {"from": "https://outlook.live.com/", "to": "https://outlook.live.com/mail/", "name": "Outlook", "legacyName": "Outlook"},
  ],
};
