'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const locales = path.join(root, 'js', 'locales');
const languages = ['en', 'fr', 'es', 'de', 'it', 'ru', 'ar', 'pt'];
const translations = Object.fromEntries(languages.map(language => [language, {}]));
for (const filename of fs.readdirSync(locales).sort()) {
    const match = filename.match(/^.+-(en|fr|es|de|it|ru|ar|pt)\.json$/);
    if (!match) continue;
    const dictionary = JSON.parse(fs.readFileSync(path.join(locales, filename), 'utf8'));
    for (const [key, value] of Object.entries(dictionary)) {
        if (typeof value !== 'string' || !value.trim()) throw new Error(filename + ': missing text for ' + key);
        if (Object.prototype.hasOwnProperty.call(translations[match[1]], key)) throw new Error(filename + ': duplicate key ' + key);
        translations[match[1]][key] = value;
    }
}
const referenceKeys = Object.keys(translations.fr).sort();
const params = text => Array.from(text.matchAll(/\{([a-zA-Z0-9_]+)\}/g), match => match[1]).sort().join(',');
for (const language of languages) {
    if (JSON.stringify(Object.keys(translations[language]).sort()) !== JSON.stringify(referenceKeys)) {
        throw new Error(language + ': keys differ from French: ' + referenceKeys.filter(key => !Object.prototype.hasOwnProperty.call(translations[language], key)).join(', '));
    }
    for (const key of referenceKeys) {
        if (params(translations[language][key]) !== params(translations.fr[key])) throw new Error(language + ': placeholders differ for ' + key);
    }
}
const bundle = '/* Generated by scripts/build-locales.cjs from js/locales/*.json. */\n' +
    '(function (root, data) { if (typeof module === "object" && module.exports) module.exports = data; else root.EV_TRANSLATIONS = data; }(typeof globalThis !== "undefined" ? globalThis : this, ' + JSON.stringify(translations) + '));\n';
fs.writeFileSync(path.join(root, 'js', 'translations.js'), bundle);
console.log('Built ' + referenceKeys.length + ' translations in ' + languages.length + ' languages.');
